version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5000:80" # Map port 5000 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Optional: Mount Nginx config for live changes
    environment:
      - NODE_ENV=production
    restart: unless-stopped